apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  grafana-admin: grafana_admin
  grafana-password: grafana_pass
  grafana-secret-key: SW2YcwTIb9zpOOhoPsMm
  influxdb-user: user
  influxdb-password: password