---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb-pod
  template:
    metadata:
      labels:
        app: influxdb-pod
    spec:
      containers:
      - name: influxdb
        image: ft_services_influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influ-cont-port
        volumeMounts:
        - name: influxdb-volume
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb-pod
  ports:
  - port: 8086
    targetPort: influ-cont-port
    protocol: TCP
    name: influxdb-service-port

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi