---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft_services_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port
        env:
        - name: WPPORT
          value: "5050"
        - name: PMAPORT
          value: "5000"
        livenessProbe:
          exec:
            command:
            - /usr/sbin/pod_crash.sh
          initialDelaySeconds: 25
          periodSeconds: 25

---
  
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services_sharing_key"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: $EXTERNAL_IP
  ports:
  - port: 80
    name: http-port
    targetPort: 80
    protocol: TCP
  - port: 443
    name: https-port
    targetPort: 443
    protocol: TCP
