---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_services_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: WP_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-configmap
              key: wp-db-host
        livenessProbe:
          exec:
            command:
            - /usr/sbin/pod_crash.sh
          initialDelaySeconds: 25
          periodSeconds: 25

---
  
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services_sharing_key"
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: $EXTERNAL_IP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
