---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_services_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        env:
        - name: WP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wordpress-db-name
        - name: WP_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wordpress-mysql-db-user
        - name: WP_DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: wordpress-mysql-db-passwd
        - name: WP_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-configmap
              key: wp-db-host
        - name: WORDPRESS_SVC_IP
          value: $EXTERNAL_IP
        - name: WORDPRESS_SVC_PORT
          value: "5050"
        livenessProbe:
          exec:
            command:
            - /usr/sbin/pod_crash.sh
          initialDelaySeconds: 25
          periodSeconds: 25
        

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services_sharing_key"
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: $EXTERNAL_IP
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
